clear all;
ResponseTimes = readmatrix("SimResults/RespTime.txt");
Throughputs = readmatrix("SimResults/Throughput.txt");
Balance = Throughputs(1,:)./ResponseTimes(1,:);
N=length(ResponseTimes);
figure(1);
plot(1:N, ResponseTimes(1,1:N));
xlim([1 N]);
xticks(1:N);
figure(2);
plot(1:N, Throughputs(1,1:N));
xlim([1 N]);
xticks(1:N);
figure(3);
plot(1:N, Balance(1,1:N));
xlim([1 N]);
xticks(1:N);
xlabel({'Number of jobs'});
ylabel({'Balance'});